FROM postgres:17

RUN apt-get update &&  \ 
  apt-get -y install postgresql-17-cron && \ 
  apt-get clean \ 
  && rm -rf /var/lib/apt/lists/*

COPY ./docker/pg_config/postgres.conf /etc/postgresql/postgresql.conf

CMD [ "-c", "config_file=/etc/postgresql/postgresql.conf" ]